require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 2.7
  DisplayStyleGuide: true
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'

ThreadSafety/InstanceVariableInClassMethod:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

ThreadSafety/NewThread:
  Exclude:
    - 'spec/**/*'

Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - macros
    - public_attribute_macros
    - public_delegate
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Rails:
  Enabled: true

Rails/ApplicationController:
  Enabled: false

Rails/ApplicationMailer:
  Enabled: false

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_sql
    - find_by_address

Rails/FilePath:
  EnforcedStyle: arguments

Rails/RakeEnvironment:
  Enabled: false

Rails/TimeZone:
  EnforcedStyle: flexible

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - test
    - development
    - staging
    - production
    - alpha

Rails/SkipsModelValidations:
  AllowedMethods:
    - decrement!
    - increment!
    - update_all
    - touch
  Exclude:
    - 'spec/**/*'

Rails/HttpStatus:
  EnforcedStyle: numeric

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

# currently too many false positivs
Rails/Pluck:
  Enabled: false

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/WhereExists:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - Capfile
    - Guardfile
    - Rakefile
    - config.ru

Style/SingleLineBlockParams:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/AndOr:
  EnforcedStyle: conditionals

Style/MixinUsage:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/DateTime:
  AllowCoercion: true

Style/GuardClause:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

# 118 is the maximum line length in the GitHub UI
Layout/LineLength:
  Max: 118
  Exclude:
    - 'Gemfile'

Metrics/ModuleLength:
  Max: 500

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'app/views/**/*.arb'
    - 'Guardfile'
  ExcludedMethods:
    - swagger_api

Metrics/ParameterLists:
  CountKeywordArgs: false

# We don't want to enforce this in spec because it would break
# identification for chained expect change.
Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/**/*'

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/SuppressedException:
  Enabled: false

Lint/Loop:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Naming/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'
    - 'Rakefile'

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Performance/UnfreezeString:
  Enabled: false

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

RSpec/PredicateMatcher:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

FactoryBot/CreateList:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: false

Style/HashLikeCase:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false

Style/RedundantAssignment:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Style/ClassEqualityComparison:
  Enabled: true
